modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/right-click-harvest/issues"

[[mods]]
modId = "rightclickharvest"
version = "${file.jarVersion}"
displayName = "Right Click Harvest"
displayURL = "https://github.com/JamCoreModding/right-click-harvest"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Right click crops to harvest them - with style.
'''

[[dependencies.rightclickharvest]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "jamlib"
mandatory = true
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"
