name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Enable Caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/machete-build
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: gradle

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build
        run: ./gradlew clean forge:build fabric:build quilt:build

      - name: Capture Fabric Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Fabric Artifacts
          path: fabric/build/libs/

      - name: Capture Quilt Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Quilt Artifacts
          path: quilt/build/libs/

      - name: Capture Forge Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Forge Artifacts
          path: forge/build/libs/
